
spring:
  devtools:
    livereload:
      port: 8081
  config:
    import: "classpath:bot-config.yml, classpath:rabbit-config.yml, classpath:db_config.yml"
server:
  port: 8085
  ssl:
    enabled: false
